### ISSUE TITLE
Time class

### ISSUE THREAD

**Issue by slugbyte** [BrianL3/DoctorWizard#88]
We Need to consolidate time in to a singleton class that provides geters for the important time values

delta time
current time "time from update()"
ellapsed time  "amout of time game has played, pauses when game is not on, or game pause"

**Comment by BrianL3** [comment]
I could split the time out into a singleton game clock.

**Comment by slugbyte** [comment]
WHOOOOP we have a singleton time class with an ellapsted time variable 
game time dosent break when the app enters background 
::::::::))))))
